# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AAC-Pvoice
version:      0.8
version_from: lib/AAC/Pvoice.pm
installdirs:  site
requires:
    Device::ParallelPort:          0
    Device::ParallelPort::drv::win32: 0
    Wx:                            0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
